### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [NoahKrill11/StockRecords#1]
Hi,<br><br>url : https://github.com/NoahKrill11/StockRecords/blob/74a341208fb83afdab97e5eb516c6736a70904c2/Project/Default.aspx.cs <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by NoahKrill11** [comment]
Confused as to what you mean

**Comment by shaybenb** [comment]
as you can see you DB password are in clear text
![image](https://user-images.githubusercontent.com/46863888/104810403-f349b080-57fc-11eb-8857-bde4f3b86b13.png)

**Comment by shaybenb** [comment]
Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
